### ISSUE TITLE
CHECKLIST

### ISSUE THREAD

**Issue by soophikat** [42party/UNDRGRND#54]
### checkliist de coisas q lembro aqui

- [x] rodar o player pra a rotação N W S ou E
- [x] add textura
- [x] mover a camera na setinha e o player no wasd
- [x] pintar o floor e ceiling com a cor do .cub
> só to lembrando disso q falta.
> não cria branch disso
